import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "./globals.css";

import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/shared/app-sidebar";
import BottomMenuBar from "@/components/shared/BottomMenuBar";
import { VideoVolumeProvider } from "@/components/shared/VideoVolumeProvider";

const inter = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-screen bg-background text-foreground">
        <VideoVolumeProvider>
          <SidebarProvider>

            <div className="mx-auto flex justify-center min-h-screen w-full max-w-7xl">

              <AppSidebar />


              <main className="flex w-full min-w-0 max-w-2xl flex-1 flex-col border-x border-border min-h-screen">
                {children}
              </main>

              <aside className="hidden lg:block w-80 xl:w-96 px-6 py-4">
                <div className="sticky top-4 flex flex-col gap-4">

                  <div className="rounded-xl border border-border bg-card p-4 text-card-foreground shadow-sm">
                    <h3 className="font-semibold text-lg mb-2">
                      Widgets Area
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      Right sidebar content goes here.
                    </p>
                  </div>
                </div>
              </aside>

            </div>

            <BottomMenuBar />
          </SidebarProvider>

          <ToastContainer />
        </VideoVolumeProvider>
      </body>
    </html>
  );
}